#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AccentColor.Droid.Resource", IsApplication=true)]

namespace AccentColor.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int accent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int primary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int primary_dark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int apptheme_edit_text_holo_light = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int apptheme_textfield_activated_holo_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int apptheme_textfield_default_holo_light = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int apptheme_textfield_disabled_focused_holo_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int apptheme_textfield_disabled_holo_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int apptheme_textfield_focused_holo_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f030000
			public const int AppTheme = 2130903040;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
